In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv("Data\Export and Import of goods records of 2003 1.csv",encoding="unicode_escape")
df

,Hs Code,Hs Description,Date Processed,Items Number,Number of Package,Goods Description1,Items Cif Ghc,Amount Paid Ghc,Country Destination
0,3.054900e+08,Smoked fish (excl. salmon and herrings),10/10/2003 03:02PM,2,100,SMOKED FISH,2111.52,0.0,CA
1,NaN,NaN,11/28/2003 03:03PM,1,37,SMOKED FISH,1546.36,0.0,GH
2,NaN,NaN,12/4/2003 03:32PM,1,6,SMOKED FISH,390.11,0.0,US
3,3.076000e+08,Snails other than sea snails,11/3/2003 05:51PM,1,4,SNAILS,87.81,0.0,GB
4,7.031000e+08,"Onions and shallots, fresh or chilled",10/15/2003 01:51PM,4,8,ONIONS,21.12,0.0,GB
...,...,...,...,...,...,...,...,...,...
493,NaN,NaN,12/22/2003 04:15PM,1,4,WOODEN,2435.69,0.0,GH
494,NaN,NaN,12/29/2003 04:45PM,1,23,WOODEN TILES,177.45,0.0,GH
495,9.407000e+09,PERSONAL EFFECTS,11/28/2003 03:03PM,1,1,PERSONAL EFFECTS,119.38,0.0,GH
496,NaN,NaN,12/1/2003 04:08PM,1,1,AFRICAN CLOTHING,87.61,0.0,GH
497,NaN,NaN,12/19/2003 02:48PM,1,1,PERSONAL EFFECTS,86.48,0.0,GH

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Hs Code               51 non-null     float64
 1   Hs  Description       51 non-null     object
 2   Date Processed        269 non-null    object
 3   Items Number          498 non-null    int64
 4   Number of Package     498 non-null    int64
 5   Goods Description1    498 non-null    object
 6   Items Cif Ghc         498 non-null    float64
 7   Amount Paid Ghc       498 non-null    float64
 8   Country  Destination  268 non-null    object
dtypes: float64(3), int64(2), object(4)
memory usage: 35.1+ KB